version: '3'

services:
  redis:
    image: redis:latest
    container_name: sass_redis
    ports:
        - "6379:6379"
    volumes:
      - ./database/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  mysql:
    image: mysql:5.6
    container_name: sass_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
        - "3306:3306"
    volumes:
        - ./database/mysql/backup:/backup
        - ./database/mysql/data:/var/lib/mysql
        - ./database/mysql/config:/etc/mysql/conf.d
  saas_jfu:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile74
    image: saas_jfu:tag
    tty: true
    container_name: saas_jfu
    ports:
      - "8080:80"
    volumes:
      - ./projects/saas_jfu:/var/www/html
      - ./apache/000-default-index.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini